### ISSUE TITLE
Package fortuneglobe/icehawk is abandoned.

### ISSUE THREAD

**Issue by rdonadono** [hollodotme/readis#1]
Hi,

the composer command return this message at the end of the process:

> Package fortuneglobe/icehawk is abandoned, you should avoid using it. Use icehawk/icehawk instead.

**Comment by hollodotme** [comment]
I updated the composer dependencies accordingly and released [v1.1.3](https://github.com/hollodotme/readis/releases/tag/v1.1.3)

Thanks for using readis!

BTW: I am planning to release a v2.0.0 for PHP >= 7.0 and an interactive installer for readis soon.

**Comment by rdonadono** [comment]
Thank's for your job!

The version 2.0 will write to redis?
You have foreseen this possibility?

**Comment by hollodotme** [comment]
@phpwriter No this is not planned. Readis will remain a read only tool. I also think a write tool would be very complex because of the many ways you can send data to redis (key-value, hashes, different serialization, and so on...). Maybe one day there will be a Wredis ;)

What I basically plan to do in 2.0 is:
* Refactoring for PHP 7.0
* Making the readis library code a composer dependency
* Creating the user-defined code (configs) with an interactive installer (via composer)
    This will be way easier to install!
* Providing an option for an authentication (login)
* An option to unserialize the content of a key/hash in the detail view (with `json_decode()` and `unserialize()`) to get better insights
